/Users/zhoushoujian/lvgl_test/include
/Users/zhoushoujian/lvgl_test/src
/Users/zhoushoujian/lvgl_test/lib/wifi
/Users/zhoushoujian/lvgl_test/lib/ui
/Users/zhoushoujian/lvgl_test/.pio/libdeps/esp32dev/ArduinoJson/src
/Users/zhoushoujian/lvgl_test/.pio/libdeps/esp32dev/ArduinoWebsockets/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/HTTPClient/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src
/Users/zhoushoujian/lvgl_test/.pio/libdeps/esp32dev/lvgl
/Users/zhoushoujian/lvgl_test/.pio/libdeps/esp32dev/lvgl/src
/Users/zhoushoujian/lvgl_test/.pio/libdeps/esp32dev/TFT_eSPI
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/LittleFS/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/SPIFFS/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/FS/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/SPI/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/newlib/platform_include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/freertos/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/freertos/include/esp_additions/freertos
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/freertos/port/xtensa/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/freertos/include/esp_additions
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_hw_support/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_hw_support/include/soc
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_hw_support/include/soc/esp32
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_hw_support/port/esp32
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_hw_support/port/esp32/private_include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/heap/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/log/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/lwip/include/apps
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/lwip/include/apps/sntp
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/lwip/lwip/src/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/lwip/port/esp32/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/lwip/port/esp32/include/arch
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/soc/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/soc/esp32
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/soc/esp32/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/hal/esp32/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/hal/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/hal/platform_port/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_rom/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_rom/include/esp32
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_rom/esp32
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_common/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_system/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_system/port/soc
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_system/port/public_compat
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp32/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/xtensa/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/xtensa/esp32/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/driver/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/driver/esp32/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_pm/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_ringbuf/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/efuse/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/efuse/esp32/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/vfs/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_wifi/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_event/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_netif/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_eth/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/tcpip_adapter/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_phy/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_phy/esp32/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_ipc/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/app_trace/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_timer/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/mbedtls/port/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/mbedtls/mbedtls/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/mbedtls/esp_crt_bundle/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/app_update/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/spi_flash/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bootloader_support/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/nvs_flash/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/pthread/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_gdbstub/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_gdbstub/xtensa
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_gdbstub/esp32
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espcoredump/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espcoredump/include/port/xtensa
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/wpa_supplicant/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/wpa_supplicant/port/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/wpa_supplicant/esp_supplicant/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/ieee802154/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/console
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/asio/asio/asio/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/asio/port/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/common/osi/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/include/esp32/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/common/api/include/api
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/common/btc/profile/esp/blufi/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/common/btc/profile/esp/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/host/bluedroid/api/include/api
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/esp_ble_mesh/mesh_common/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/esp_ble_mesh/mesh_common/tinycrypt/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/esp_ble_mesh/mesh_core
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/esp_ble_mesh/mesh_core/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/esp_ble_mesh/mesh_core/storage
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/esp_ble_mesh/btc/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/esp_ble_mesh/mesh_models/common/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/esp_ble_mesh/mesh_models/client/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/esp_ble_mesh/mesh_models/server/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/esp_ble_mesh/api/core/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/esp_ble_mesh/api/models/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/esp_ble_mesh/api
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/cbor/port/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/unity/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/unity/unity/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/cmock/CMock/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/coap/port/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/coap/libcoap/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/nghttp/port/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/nghttp/nghttp2/lib/includes
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp-tls
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp-tls/esp-tls-crypto
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_adc_cal/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_hid/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/tcp_transport/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_http_client/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_http_server/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_https_ota/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_https_server/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_lcd/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_lcd/interface
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/protobuf-c/protobuf-c
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/protocomm/include/common
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/protocomm/include/security
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/protocomm/include/transports
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/mdns/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_local_ctrl/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/sdmmc/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_serial_slave_link/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_websocket_client/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/expat/expat/expat/lib
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/expat/port/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/wear_levelling/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/fatfs/diskio
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/fatfs/vfs
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/fatfs/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/freemodbus/freemodbus/common/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/idf_test/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/idf_test/include/esp32
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/jsmn/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/json/cJSON
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/libsodium/libsodium/src/libsodium/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/libsodium/port_include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/mqtt/esp-mqtt/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/openssl/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/perfmon/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/spiffs/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/ulp/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/wifi_provisioning/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/rmaker_common/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_diagnostics/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/rtc_store/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_insights/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/json_parser/upstream/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/json_parser/upstream
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/json_generator/upstream
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_schedule/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp_secure_cert_mgr/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_rainmaker/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/gpio_button/button/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/qrcode/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/ws2812_led
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_littlefs/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp-dl/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp-dl/include/tool
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp-dl/include/typedef
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp-dl/include/image
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp-dl/include/math
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp-dl/include/nn
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp-dl/include/layer
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp-dl/include/detect
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp-dl/include/model_zoo
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp-sr/src/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp-sr/esp-tts/esp_tts_chinese/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp-sr/include/esp32
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp32-camera/driver/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp32-camera/conversions/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/dotprod/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/support/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/windows/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/windows/hann/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/windows/blackman/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/windows/blackman_harris/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/windows/blackman_nuttall/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/windows/nuttall/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/windows/flat_top/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/iir/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/fir/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/math/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/math/add/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/math/sub/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/math/mul/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/math/addc/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/math/mulc/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/math/sqrt/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/matrix/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/fft/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/dct/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/conv/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/common/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/kalman/ekf/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/kalman/ekf_imu13states/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/fb_gfx/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/dio_qspi/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/cores/esp32
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/variants/esp32
/Users/zhoushoujian/lvgl_test/.pio/libdeps/esp32dev/Unity/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/ArduinoOTA/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/AsyncUDP/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/BLE/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/BluetoothSerial/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/DNSServer/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/EEPROM/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/ESP32/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/ESPmDNS/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/Ethernet/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/FFat/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/HTTPUpdate/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/HTTPUpdateServer/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/I2S/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/Insights/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/NetBIOS/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/Preferences/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/RainMaker/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/SD/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/SD_MMC/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/SimpleBLE/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/Ticker/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/USB/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/Update/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/WebServer/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/WiFiProv/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/Wire/src/Users/zhoushoujian/lvgl_test/include
/Users/zhoushoujian/lvgl_test/src
/Users/zhoushoujian/lvgl_test/lib/wifi
/Users/zhoushoujian/lvgl_test/lib/my_init
/Users/zhoushoujian/lvgl_test/lib/ui
/Users/zhoushoujian/lvgl_test/.pio/libdeps/esp32dev/ArduinoJson/src
/Users/zhoushoujian/lvgl_test/.pio/libdeps/esp32dev/ArduinoWebsockets/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/HTTPClient/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src
/Users/zhoushoujian/lvgl_test/.pio/libdeps/esp32dev/lvgl
/Users/zhoushoujian/lvgl_test/.pio/libdeps/esp32dev/lvgl/src
/Users/zhoushoujian/lvgl_test/.pio/libdeps/esp32dev/TFT_eSPI
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/LittleFS/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/SPIFFS/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/FS/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/SPI/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/newlib/platform_include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/freertos/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/freertos/include/esp_additions/freertos
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/freertos/port/xtensa/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/freertos/include/esp_additions
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_hw_support/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_hw_support/include/soc
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_hw_support/include/soc/esp32
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_hw_support/port/esp32
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_hw_support/port/esp32/private_include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/heap/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/log/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/lwip/include/apps
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/lwip/include/apps/sntp
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/lwip/lwip/src/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/lwip/port/esp32/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/lwip/port/esp32/include/arch
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/soc/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/soc/esp32
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/soc/esp32/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/hal/esp32/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/hal/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/hal/platform_port/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_rom/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_rom/include/esp32
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_rom/esp32
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_common/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_system/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_system/port/soc
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_system/port/public_compat
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp32/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/xtensa/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/xtensa/esp32/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/driver/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/driver/esp32/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_pm/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_ringbuf/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/efuse/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/efuse/esp32/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/vfs/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_wifi/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_event/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_netif/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_eth/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/tcpip_adapter/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_phy/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_phy/esp32/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_ipc/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/app_trace/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_timer/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/mbedtls/port/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/mbedtls/mbedtls/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/mbedtls/esp_crt_bundle/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/app_update/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/spi_flash/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bootloader_support/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/nvs_flash/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/pthread/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_gdbstub/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_gdbstub/xtensa
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_gdbstub/esp32
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espcoredump/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espcoredump/include/port/xtensa
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/wpa_supplicant/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/wpa_supplicant/port/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/wpa_supplicant/esp_supplicant/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/ieee802154/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/console
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/asio/asio/asio/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/asio/port/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/common/osi/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/include/esp32/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/common/api/include/api
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/common/btc/profile/esp/blufi/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/common/btc/profile/esp/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/host/bluedroid/api/include/api
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/esp_ble_mesh/mesh_common/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/esp_ble_mesh/mesh_common/tinycrypt/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/esp_ble_mesh/mesh_core
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/esp_ble_mesh/mesh_core/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/esp_ble_mesh/mesh_core/storage
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/esp_ble_mesh/btc/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/esp_ble_mesh/mesh_models/common/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/esp_ble_mesh/mesh_models/client/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/esp_ble_mesh/mesh_models/server/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/esp_ble_mesh/api/core/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/esp_ble_mesh/api/models/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/bt/esp_ble_mesh/api
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/cbor/port/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/unity/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/unity/unity/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/cmock/CMock/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/coap/port/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/coap/libcoap/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/nghttp/port/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/nghttp/nghttp2/lib/includes
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp-tls
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp-tls/esp-tls-crypto
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_adc_cal/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_hid/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/tcp_transport/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_http_client/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_http_server/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_https_ota/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_https_server/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_lcd/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_lcd/interface
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/protobuf-c/protobuf-c
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/protocomm/include/common
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/protocomm/include/security
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/protocomm/include/transports
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/mdns/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_local_ctrl/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/sdmmc/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_serial_slave_link/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_websocket_client/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/expat/expat/expat/lib
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/expat/port/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/wear_levelling/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/fatfs/diskio
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/fatfs/vfs
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/fatfs/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/freemodbus/freemodbus/common/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/idf_test/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/idf_test/include/esp32
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/jsmn/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/json/cJSON
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/libsodium/libsodium/src/libsodium/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/libsodium/port_include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/mqtt/esp-mqtt/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/openssl/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/perfmon/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/spiffs/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/ulp/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/wifi_provisioning/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/rmaker_common/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_diagnostics/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/rtc_store/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_insights/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/json_parser/upstream/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/json_parser/upstream
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/json_generator/upstream
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_schedule/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp_secure_cert_mgr/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_rainmaker/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/gpio_button/button/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/qrcode/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/ws2812_led
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_littlefs/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp-dl/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp-dl/include/tool
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp-dl/include/typedef
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp-dl/include/image
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp-dl/include/math
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp-dl/include/nn
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp-dl/include/layer
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp-dl/include/detect
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp-dl/include/model_zoo
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp-sr/src/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp-sr/esp-tts/esp_tts_chinese/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp-sr/include/esp32
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp32-camera/driver/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp32-camera/conversions/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/dotprod/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/support/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/windows/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/windows/hann/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/windows/blackman/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/windows/blackman_harris/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/windows/blackman_nuttall/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/windows/nuttall/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/windows/flat_top/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/iir/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/fir/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/math/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/math/add/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/math/sub/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/math/mul/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/math/addc/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/math/mulc/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/math/sqrt/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/matrix/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/fft/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/dct/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/conv/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/common/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/kalman/ekf/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/espressif__esp-dsp/modules/kalman/ekf_imu13states/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/fb_gfx/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/dio_qspi/include
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/cores/esp32
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/variants/esp32
/Users/zhoushoujian/lvgl_test/.pio/libdeps/esp32dev/Unity/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/ArduinoOTA/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/AsyncUDP/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/BLE/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/BluetoothSerial/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/DNSServer/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/EEPROM/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/ESP32/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/ESPmDNS/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/Ethernet/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/FFat/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/HTTPUpdate/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/HTTPUpdateServer/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/I2S/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/Insights/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/NetBIOS/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/Preferences/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/RainMaker/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/SD/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/SD_MMC/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/SimpleBLE/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/Ticker/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/USB/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/Update/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/WebServer/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/WiFiProv/src
/Users/zhoushoujian/.platformio/packages/framework-arduinoespressif32/libraries/Wire/src