// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Screen1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x5B5B5B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_speed = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_speed, 150);
lv_obj_set_height( ui_speed, 150);
lv_obj_set_x( ui_speed, 10 );
lv_obj_set_y( ui_speed, -10 );
lv_obj_set_align( ui_speed, LV_ALIGN_BOTTOM_LEFT );
lv_arc_set_range(ui_speed, 0,199);
lv_arc_set_value(ui_speed, 0);
lv_obj_remove_style(ui_speed, NULL, LV_PART_KNOB);
lv_obj_clear_flag( ui_speed, LV_OBJ_FLAG_CLICKABLE );    // 去除点击属性
// lv_arc_set_change_rate(ui_speed, 10);

lv_obj_set_style_arc_color(ui_speed, lv_color_hex(0x40FFDF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_speed, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_speed2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_speed2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_speed2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_speed2, -76 );
lv_obj_set_y( ui_speed2, -3 );
lv_obj_set_align( ui_speed2, LV_ALIGN_CENTER );
lv_label_set_text(ui_speed2,"0");
lv_obj_set_style_text_color(ui_speed2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_speed2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_speed2, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -75 );
lv_obj_set_y( ui_Label1, 35 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"km/h");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ood = lv_img_create(ui_Screen1);
lv_img_set_src(ui_ood, &ui_img_zuoyedaolu_png);
lv_obj_set_width( ui_ood, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ood, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ood, 28 );
lv_obj_set_y( ui_ood, -50 );
lv_obj_set_align( ui_ood, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ood, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ood, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_location = lv_img_create(ui_Screen1);
lv_img_set_src(ui_location, &ui_img_965679087);
lv_obj_set_width( ui_location, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_location, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_location, -107 );
lv_obj_set_y( ui_location, 69 );
lv_obj_set_align( ui_location, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_location, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_location, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_suzhou = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_suzhou, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_suzhou, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_suzhou, -62 );
lv_obj_set_y( ui_suzhou, 68 );
lv_obj_set_align( ui_suzhou, LV_ALIGN_CENTER );
lv_label_set_text(ui_suzhou,"SuZhou");
lv_obj_set_style_text_color(ui_suzhou, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_suzhou, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_suzhou, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_moto = lv_img_create(ui_Screen1);
lv_img_set_src(ui_moto, &ui_img_1753992569);
lv_obj_set_width( ui_moto, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_moto, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_moto, 29 );
lv_obj_set_y( ui_moto, 3 );
lv_obj_set_align( ui_moto, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_moto, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_moto, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_totalkm = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_totalkm, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_totalkm, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_totalkm, 134 );
lv_obj_set_y( ui_totalkm, -45 );
lv_obj_set_align( ui_totalkm, LV_ALIGN_CENTER );
lv_label_set_text(ui_totalkm,"km");
lv_obj_set_style_text_color(ui_totalkm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_totalkm, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_totalkm, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_km = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_km, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_km, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_km, 87 );
lv_obj_set_y( ui_km, -47 );
lv_obj_set_align( ui_km, LV_ALIGN_CENTER );
lv_label_set_text(ui_km,"32.28");
lv_obj_set_style_text_color(ui_km, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_km, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_km, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_roll = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_roll, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_roll, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_roll, 86 );
lv_obj_set_y( ui_roll, 2 );
lv_obj_set_align( ui_roll, LV_ALIGN_CENTER );
lv_label_set_text(ui_roll,"-8.32");
lv_obj_set_style_text_color(ui_roll, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_roll, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_roll, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_du = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_du, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_du, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_du, 127 );
lv_obj_set_y( ui_du, 1 );
lv_obj_set_align( ui_du, LV_ALIGN_CENTER );
lv_label_set_text(ui_du,"°");
lv_obj_set_style_text_color(ui_du, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_du, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_du, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_luxiang = lv_img_create(ui_Screen1);
lv_img_set_src(ui_luxiang, &ui_img_luxiang_png);
lv_obj_set_width( ui_luxiang, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_luxiang, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_luxiang, 30 );
lv_obj_set_y( ui_luxiang, 53 );
lv_obj_set_align( ui_luxiang, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_luxiang, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_luxiang, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_recordtime = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_recordtime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_recordtime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_recordtime, 101 );
lv_obj_set_y( ui_recordtime, 50 );
lv_obj_set_align( ui_recordtime, LV_ALIGN_CENTER );
lv_label_set_text(ui_recordtime,"00'24'32");
lv_obj_set_style_text_color(ui_recordtime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_recordtime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_recordtime, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_speed, ui_event_speed, LV_EVENT_ALL, NULL);

}
